const defaultRes = {
  code: 200,
  message: '请求成功。客户端向服务器请求数据，服务器返回相关数据',
  data: {
    adList: [
      {
        locationShowTypeCode: 'GGWZXSS_LBXS',
        locationName: '薯片推广企业服务活动页面4',
        locationId: '8058282203740438528',
        locationAddressCode: '',
        sortMaterialList: [
          {
            locationSort: 1,
            materialList: [
              {
                materialTypeCode: 'GGLX_TP',
                materialUrl:
                  'https://cdn.shupian.cn/sp/cms/67aaudpk9a00000.png',
                imgLink: '',
                materialLink: 'baidu.com',
                materialCode: 'src113429',
                materialHeight: 44,
                materialId: '8058277673137143808',
                materialDescription: '99元团,品质拼团',
                materialName: '薯片推广企业服务活动页面',
                androidLink: '',
                materialWidth: 44,
                iosLink: '',
                linkType: 2,
                wapLink: '',
                executeParam: '',
              },
            ],
          },
          {
            locationSort: 2,
            materialList: [
              {
                materialTypeCode: 'GGLX_TP',
                materialUrl:
                  'https://cdn.shupian.cn/sp/cms/bodpjcecezk0000.png',
                imgLink: '',
                materialLink: 'baidu.com',
                materialCode: 'src113430',
                materialHeight: 44,
                materialId: '8058279836508815360',
                materialDescription: '先服务后收费,平台担保放心购',
                materialName: '薯片推广企业服务活动页面2',
                androidLink: '',
                materialWidth: 44,
                iosLink: '',
                linkType: 2,
                wapLink: '',
                executeParam: '',
              },
            ],
          },
          {
            locationSort: 3,
            materialList: [
              {
                materialTypeCode: 'GGLX_TP',
                materialUrl:
                  'https://cdn.shupian.cn/sp/cms/bx3wgaos1eg0000.png',
                imgLink: '',
                materialLink: 'baidu.com',
                materialCode: 'src113435',
                materialHeight: 44,
                materialId: '8058281175607476224',
                materialDescription: '领劵中心,服务销冠',
                materialName: '薯片推广企业服务活动页面3',
                androidLink: '',
                materialWidth: 44,
                iosLink: '',
                linkType: 2,
                wapLink: '',
                executeParam: '',
              },
            ],
          },
          {
            locationSort: 4,
            materialList: [
              {
                materialTypeCode: 'GGLX_TP',
                materialUrl:
                  'https://cdn.shupian.cn/sp/cms/1z6y1kdb4z28000.png',
                imgLink: '',
                materialLink: 'baidu.com',
                materialCode: 'src113436',
                materialHeight: 44,
                materialId: '8058281687744577536',
                materialDescription: '帮找服务,免费高效',
                materialName: '薯片推广企业服务活动页面4',
                androidLink: '',
                materialWidth: 44,
                iosLink: '',
                linkType: 2,
                wapLink: '',
                executeParam: '',
              },
            ],
          },
        ],
        locationCode: 'ad113257',
        locationCodeLocType: 2,
      },
      {
        locationShowTypeCode: 'GGWZXSS_LBXS',
        locationName: '薯片推广企业服务-直播',
        locationId: '8058269301545435136',
        locationAddressCode: '',
        sortMaterialList: [
          {
            locationSort: 1,
            materialList: [
              {
                materialTypeCode: 'GGLX_TP',
                materialUrl:
                  'https://cdn.shupian.cn/sp/cms/fazrcq91xyo0000.png',
                imgLink: '',
                materialLink: 'baidu.com',
                materialCode: 'src113427',
                materialHeight: 160,
                materialId: '8058269143176904704',
                materialDescription: '企服直播,行业大牛助力企业',
                materialName: '薯片推广企业服务-直播',
                androidLink: '',
                materialWidth: 309,
                iosLink: '',
                linkType: 2,
                wapLink: '',
                executeParam: '',
              },
            ],
          },
          {
            locationSort: 2,
            materialList: [
              {
                materialTypeCode: 'GGLX_TP',
                materialUrl:
                  'https://cdn.shupian.cn/sp/cms/dg9q4fyuod40000.png',
                imgLink: '',
                materialLink: 'baidu.com',
                materialCode: 'src113428',
                materialHeight: 160,
                materialId: '8058273647381250048',
                materialDescription: '1000万补贴,万款服务全补贴',
                materialName: '薯片推广企业服务-补贴',
                androidLink: '',
                materialWidth: 309,
                iosLink: '',
                linkType: 2,
                wapLink: '',
                executeParam: '',
              },
            ],
          },
        ],
        locationCode: 'ad113252',
        locationCodeLocType: 2,
      },
      {
        locationShowTypeCode: 'GGWZXSS_LBXS',
        locationName: '薯片推广企业服务新人专属礼页面',
        locationId: '8058259796912832512',
        locationAddressCode: '',
        sortMaterialList: [
          {
            locationSort: 1,
            materialList: [
              {
                materialTypeCode: 'GGLX_TP',
                materialUrl:
                  'https://cdn.shupian.cn/sp/cms/8kss63uazk00000.png',
                imgLink: '',
                materialLink: 'baidu.com',
                materialCode: 'src113437',
                materialHeight: 140,
                materialId: '8058552782175404032',
                materialDescription: '有限公司注册,0元',
                materialName: '薯片推广企业服务新人专属礼页面',
                androidLink: '',
                materialWidth: 140,
                iosLink: '',
                linkType: 2,
                wapLink: '',
                executeParam: '',
              },
            ],
          },
          {
            locationSort: 2,
            materialList: [
              {
                materialTypeCode: 'GGLX_TP',
                materialUrl:
                  'https://cdn.shupian.cn/sp/cms/e313jj7lz680000.png',
                imgLink: '',
                materialLink: 'baidu.com',
                materialCode: 'src113438',
                materialHeight: 140,
                materialId: '8058553276566405120',
                materialDescription: '一般纳税人,1元/月',
                materialName: '薯片推广企业服务新人专属礼页面2',
                androidLink: '',
                materialWidth: 140,
                iosLink: '',
                linkType: 2,
                wapLink: '',
                executeParam: '',
              },
            ],
          },
          {
            locationSort: 3,
            materialList: [
              {
                materialTypeCode: 'GGLX_TP',
                materialUrl: 'https://cdn.shupian.cn/sp/cms/nao4zl9dayo000.png',
                imgLink: '',
                materialLink: 'baidu.com',
                materialCode: 'src113439',
                materialHeight: 140,
                materialId: '8058553571086237696',
                materialDescription: '服务代金劵,600元',
                materialName: '薯片推广企业服务新人专属礼页面3',
                androidLink: '',
                materialWidth: 140,
                iosLink: '',
                linkType: 2,
                wapLink: '',
                executeParam: '',
              },
            ],
          },
        ],
        locationCode: 'ad113250',
        locationCodeLocType: 2,
      },
    ],
    navs: {
      nav100057: [
        {
          id: '8058251162430537728',
          code: 'nav010435',
          platformCode: 'COMDIC_PLATFORM_CRISPS',
          platformName: '薯片',
          terminalCode: 'COMDIC_TERMINAL_WAP',
          terminalName: 'WAP',
          categoryId: '8058243860654784512',
          categoryCode: 'nav100057',
          name: '工商变更',
          navigationImageUrl:
            'https://cdn.shupian.cn/sp/cms/28vcmynobbgg000.png',
          navigationWay: 2,
          url: 'baidu.com',
          imageUrl: '',
          androidRoute: '',
          iosRoute: '',
          wapRoute: '',
          executionParameters: '',
          description: '',
          sort: 0,
          status: 1,
        },
        {
          id: '8058251023389360128',
          code: 'nav010425',
          platformCode: 'COMDIC_PLATFORM_CRISPS',
          platformName: '薯片',
          terminalCode: 'COMDIC_TERMINAL_WAP',
          terminalName: 'WAP',
          categoryId: '8058243860654784512',
          categoryCode: 'nav100057',
          name: '税务筹划',
          navigationImageUrl:
            'https://cdn.shupian.cn/sp/cms/3irfndyikeo0000.png',
          navigationWay: 2,
          url: 'baidu.com',
          imageUrl: '',
          androidRoute: '',
          iosRoute: '',
          wapRoute: '',
          executionParameters: '',
          description: '',
          sort: 0,
          status: 1,
        },
        {
          id: '8058250745302810624',
          code: 'nav010420',
          platformCode: 'COMDIC_PLATFORM_CRISPS',
          platformName: '薯片',
          terminalCode: 'COMDIC_TERMINAL_APP',
          terminalName: 'APP',
          categoryId: '8058243860654784512',
          categoryCode: 'nav100057',
          name: '版权服务',
          navigationImageUrl:
            'https://cdn.shupian.cn/sp/cms/7htpl4fpqyw0000.png',
          navigationWay: 2,
          url: 'baidu.com',
          imageUrl: '',
          androidRoute: '',
          iosRoute: '',
          wapRoute: '',
          executionParameters: '',
          description: '',
          sort: 0,
          status: 1,
        },
        {
          id: '8058250480302489600',
          code: 'nav010405',
          platformCode: 'COMDIC_PLATFORM_CRISPS',
          platformName: '薯片',
          terminalCode: 'COMDIC_TERMINAL_WAP',
          terminalName: 'WAP',
          categoryId: '8058243860654784512',
          categoryCode: 'nav100057',
          name: '专利服务',
          navigationImageUrl:
            'https://cdn.shupian.cn/sp/cms/dawddzt47sw0000.png',
          navigationWay: 2,
          url: 'baidu.com',
          imageUrl: '',
          androidRoute: '',
          iosRoute: '',
          wapRoute: '',
          executionParameters: '',
          description: '',
          sort: 0,
          status: 1,
        },
        {
          id: '8058250268041347072',
          code: 'nav010395',
          platformCode: 'COMDIC_PLATFORM_CRISPS',
          platformName: '薯片',
          terminalCode: 'COMDIC_TERMINAL_WAP',
          terminalName: 'WAP',
          categoryId: '8058243860654784512',
          categoryCode: 'nav100057',
          name: '商标服务',
          navigationImageUrl:
            'https://cdn.shupian.cn/sp/cms/dadizqribg00000.png',
          navigationWay: 2,
          url: 'baidu.com',
          imageUrl: '',
          androidRoute: '',
          iosRoute: '',
          wapRoute: '',
          executionParameters: '',
          description: '',
          sort: 0,
          status: 1,
        },
        {
          id: '8058249948766732288',
          code: 'nav010380',
          platformCode: 'COMDIC_PLATFORM_CRISPS',
          platformName: '薯片',
          terminalCode: 'COMDIC_TERMINAL_APP',
          terminalName: 'APP',
          categoryId: '8058243860654784512',
          categoryCode: 'nav100057',
          name: '许可证',
          navigationImageUrl:
            'https://cdn.shupian.cn/sp/cms/djug7ulkeeo0000.png',
          navigationWay: 2,
          url: 'baidu.com',
          imageUrl: '',
          androidRoute: '',
          iosRoute: '',
          wapRoute: '',
          executionParameters: '',
          description: '',
          sort: 0,
          status: 1,
        },
        {
          id: '8058249529101451264',
          code: 'nav010360',
          platformCode: 'COMDIC_PLATFORM_CRISPS',
          platformName: '薯片',
          terminalCode: 'COMDIC_TERMINAL_WAP',
          terminalName: 'WAP',
          categoryId: '8058243860654784512',
          categoryCode: 'nav100057',
          name: '资质代办',
          navigationImageUrl:
            'https://cdn.shupian.cn/sp/cms/6sz8vwty8z80000.png',
          navigationWay: 2,
          url: 'baidu.com',
          imageUrl: '',
          androidRoute: '',
          iosRoute: '',
          wapRoute: '',
          executionParameters: '',
          description: '',
          sort: 0,
          status: 1,
        },
        {
          id: '8058248818913509376',
          code: 'nav010355',
          platformCode: 'COMDIC_PLATFORM_CRISPS',
          platformName: '薯片',
          terminalCode: 'COMDIC_TERMINAL_WAP',
          terminalName: 'WAP',
          categoryId: '8058243860654784512',
          categoryCode: 'nav100057',
          name: '体系认证',
          navigationImageUrl:
            'https://cdn.shupian.cn/sp/cms/5wx8yd74a240000.png',
          navigationWay: 2,
          url: 'baidu.com',
          imageUrl: '',
          androidRoute: '',
          iosRoute: '',
          wapRoute: '',
          executionParameters: '',
          description: '',
          sort: 0,
          status: 1,
        },
        {
          id: '8058248251210268672',
          code: 'nav010350',
          platformCode: 'COMDIC_PLATFORM_CRISPS',
          platformName: '薯片',
          terminalCode: 'COMDIC_TERMINAL_WAP',
          terminalName: 'WAP',
          categoryId: '8058243860654784512',
          categoryCode: 'nav100057',
          name: '会计代理',
          navigationImageUrl:
            'https://cdn.shupian.cn/sp/cms/1bqyc48m6k1s000.png',
          navigationWay: 2,
          url: 'baidu.com',
          imageUrl: '',
          androidRoute: '',
          iosRoute: '',
          wapRoute: '',
          executionParameters: '',
          description: '',
          sort: 0,
          status: 1,
        },
        {
          id: '8058246911562153984',
          code: 'nav010315',
          platformCode: 'COMDIC_PLATFORM_CRISPS',
          platformName: '薯片',
          terminalCode: 'COMDIC_TERMINAL_WAP',
          terminalName: 'WAP',
          categoryId: '8058243860654784512',
          categoryCode: 'nav100057',
          name: '公司注册',
          navigationImageUrl:
            'https://cdn.shupian.cn/sp/cms/f5xihgz6mu80000.png',
          navigationWay: 2,
          url: 'https://www.baidu.com/',
          imageUrl: '',
          androidRoute: '',
          iosRoute: '',
          wapRoute: '',
          executionParameters: '',
          description: '',
          sort: 0,
          status: 1,
        },
      ],
    },
    productClassList: [
      {
        name: '许可证',
        code: 'FL20201224136019',
      },
      {
        name: '体系认证',
        code: 'FL20201224136060',
      },
      {
        name: '工商注册',
        code: 'FL20201224136034',
      },
      {
        name: '注销业务',
        code: 'FL20201224136048',
      },
    ],
  },
}

module.exports = { defaultRes }
